server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: redis-redistemplate
          uri: lb://redis-redistemplate
          predicates:
            - Path=/redis/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:10000/eureka/